# Site settings
title: Center for Gravitation, Cosmology and Astrophysics
email: cgca-info@uwm.edu
description: Based on Thauvette's simple template and built using Filament Group's Load CSS and Load JS and http://jch.penibelst.de/'s html compressor for optimising speed.
type: website
image: /assets/imgs/octojekyll.jpg
host: 0.0.0.0

# Server Config options
livereload: true

# SASS
sass:
  sass_dir: assets/_sass
  style: compressed

# People in the Center
#
# Each person a name, emailname, emaildomain, position, and phone
# specified here and an image file named emailname.png in 
# assets/imgs/people
# 
team:
  - name: Bruce Allen
    emailname: ballen
    emaildomain: uwm.edu
    position: Professor (Adjunct)
    phone: 414-229-XXXX
  - name: Warren Anderson
    emailname: anders15
    emaildomain: uwm.edu
    position: Visiting Professor
    phone: 414-229-3323
  - name: Patrick Brady
    emailname: prbrady
    emaildomain: uwm.edu
    position: Director and Professor
    phone: 414-229-6508
  - name: Patrick Brockill
    emailname: brockill
    emaildomain: uwm.edu
    position: Assoc. Scientist
    phone: 414-229-7274
  - name: Ian Brown
    emailname: ianbrown
    emaildomain: uwm.edu
    position: Graduate Student
    phone: 414-229-7274

# Past members of the center
#
# Each person a name, emailname, emaildomain, and position
# specified here and an image file named emailname.png in 
# assets/imgs/people
# 
former:
  - name: Luis Anchordoqui
    emailname: doqui
    emaildomain: uwm.edu
    position: Assoc. Professor

