# Site settings
title: Center for Gravitation, Cosmology and Astrophysics
email: cgca-info@uwm.edu
description: Based on Thauvette's simple template and built using Filament Group's Load CSS and Load JS and http://jch.penibelst.de/'s html compressor for optimising speed.
type: website
image: /assets/imgs/octojekyll.jpg
host: 0.0.0.0

# Server Config options
livereload: true

# SASS
sass:
  sass_dir: assets/_sass
  style: compressed

